/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as MyOutreachRouteImport } from './routes/my-outreach'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TargetsRouteImport } from './routes/targets'
import { Route as ProspectsIndexRouteImport } from './routes/prospects.index'
import { Route as ProspectsProspectIdRouteImport } from './routes/prospects.$prospectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOutreachRoute = MyOutreachRouteImport.update({
  id: '/my-outreach',
  path: '/my-outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsRoute = TargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsIndexRoute = ProspectsIndexRouteImport.update({
  id: '/prospects/',
  path: '/prospects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsProspectIdRoute = ProspectsProspectIdRouteImport.update({
  id: '/prospects/$prospectId',
  path: '/prospects/$prospectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/deals': typeof DealsRoute
  '/follow-ups': typeof FollowUpsRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/my-outreach': typeof MyOutreachRoute
  '/outreach': typeof OutreachRoute
  '/pipeline': typeof PipelineRoute
  '/proposals': typeof ProposalsRoute
  '/settings': typeof SettingsRoute
  '/targets': typeof TargetsRoute
  '/prospects/$prospectId': typeof ProspectsProspectIdRoute
  '/prospects/': typeof ProspectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/deals': typeof DealsRoute
  '/follow-ups': typeof FollowUpsRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/my-outreach': typeof MyOutreachRoute
  '/outreach': typeof OutreachRoute
  '/pipeline': typeof PipelineRoute
  '/proposals': typeof ProposalsRoute
  '/settings': typeof SettingsRoute
  '/targets': typeof TargetsRoute
  '/prospects/$prospectId': typeof ProspectsProspectIdRoute
  '/prospects': typeof ProspectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/deals': typeof DealsRoute
  '/follow-ups': typeof FollowUpsRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/my-outreach': typeof MyOutreachRoute
  '/outreach': typeof OutreachRoute
  '/pipeline': typeof PipelineRoute
  '/proposals': typeof ProposalsRoute
  '/settings': typeof SettingsRoute
  '/targets': typeof TargetsRoute
  '/prospects/$prospectId': typeof ProspectsProspectIdRoute
  '/prospects/': typeof ProspectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/deals'
    | '/follow-ups'
    | '/login'
    | '/meetings'
    | '/my-outreach'
    | '/outreach'
    | '/pipeline'
    | '/proposals'
    | '/settings'
    | '/targets'
    | '/prospects/$prospectId'
    | '/prospects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/deals'
    | '/follow-ups'
    | '/login'
    | '/meetings'
    | '/my-outreach'
    | '/outreach'
    | '/pipeline'
    | '/proposals'
    | '/settings'
    | '/targets'
    | '/prospects/$prospectId'
    | '/prospects'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/deals'
    | '/follow-ups'
    | '/login'
    | '/meetings'
    | '/my-outreach'
    | '/outreach'
    | '/pipeline'
    | '/proposals'
    | '/settings'
    | '/targets'
    | '/prospects/$prospectId'
    | '/prospects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DealsRoute: typeof DealsRoute
  FollowUpsRoute: typeof FollowUpsRoute
  LoginRoute: typeof LoginRoute
  MeetingsRoute: typeof MeetingsRoute
  MyOutreachRoute: typeof MyOutreachRoute
  OutreachRoute: typeof OutreachRoute
  PipelineRoute: typeof PipelineRoute
  ProposalsRoute: typeof ProposalsRoute
  SettingsRoute: typeof SettingsRoute
  TargetsRoute: typeof TargetsRoute
  ProspectsProspectIdRoute: typeof ProspectsProspectIdRoute
  ProspectsIndexRoute: typeof ProspectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-outreach': {
      id: '/my-outreach'
      path: '/my-outreach'
      fullPath: '/my-outreach'
      preLoaderRoute: typeof MyOutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets': {
      id: '/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof TargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects/': {
      id: '/prospects/'
      path: '/prospects'
      fullPath: '/prospects/'
      preLoaderRoute: typeof ProspectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects/$prospectId': {
      id: '/prospects/$prospectId'
      path: '/prospects/$prospectId'
      fullPath: '/prospects/$prospectId'
      preLoaderRoute: typeof ProspectsProspectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DealsRoute: DealsRoute,
  FollowUpsRoute: FollowUpsRoute,
  LoginRoute: LoginRoute,
  MeetingsRoute: MeetingsRoute,
  MyOutreachRoute: MyOutreachRoute,
  OutreachRoute: OutreachRoute,
  PipelineRoute: PipelineRoute,
  ProposalsRoute: ProposalsRoute,
  SettingsRoute: SettingsRoute,
  TargetsRoute: TargetsRoute,
  ProspectsProspectIdRoute: ProspectsProspectIdRoute,
  ProspectsIndexRoute: ProspectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
